### ISSUE TITLE
Issue with setCameraTarget(x, y, z);

### ISSUE THREAD

**Issue by danieljiwonkang98** [m-r-davari/flutter_3d_controller#33] opened 2024-10-07 14:25 UTC
Previously it worked with the version v1.3.0 I could have setCameraTarget outside of the current screen. But now when I call setCameraTarget when the glb view goes outside of the screen it resizes to fit the screen. Need fix with this.

**Comment by danieljiwonkang98** [comment] 2024-10-07 14:43
It used to work well before. The issue happens when the glb is bigger or goes off screen, then it resizes to fit the screen, making the animation weird. Need fix for this.

**Comment by m-r-davari** [comment] 2024-10-08 12:51
Hi,

Thanks for reporting, I add gesture interceptor feature in v2.0.0 it could make some effect on camera control,

would you please share you're code, I wanna reproduce your condition,

also I have send you contributor invitation.

**Comment by m-r-davari** [comment] 2024-10-14 00:26
@danieljiwonkang98  Hey, I'm going to release a new version soon, but I couldn't reproduce the issue you mentioned.
Could you please share the code or more details if the issue still exists, so I can reproduce and fix it?

**Comment by m-r-davari** [comment] 2024-10-14 15:12
I haven't received a response from you in a while. To keep the repository clean and focused, I'm closing this issue for now. 
If you have any further details or updates, feel free to reopen the issue or create a new one.

**Closed by m-r-davari** 2024-10-14 15:12 UTC
