### ISSUE TITLE
Unable to rotate the object after some time. 

### ISSUE THREAD

**Issue by gputhige** [m-r-davari/flutter_3d_controller#26] opened 2024-08-29 05:55 UTC
Hi
Great Plugin. Better than others I tried so far. I have encountered a few issues.

On load, the model can be rotated, panned and scaled. However, once the model is scaled (using two fingers vertically), the model can no longer be rotated. Even the zoom function seems to erratic. Even after trying the cameraOrbitReset, the problem continues. 

Is there anything I am doing wrong?

**Comment by m-r-davari** [comment] 2024-08-29 22:45
Hi,
Thank you for reporting issue,
could you please if I understand it correctly, when you try scale or rotating during the model loading, after model loads then rotating will not work properly?! if Its not correct then please give me exact scenario cause I need to reproduce it

**Comment by gputhige** [comment] 2024-08-30 13:55
The model loads fine at 100% and correctly on the axis. 
After the load, when I rotate, it rotates fine. Same case with scale up and down (zoom up and down), works perfectly fine. 
However, after rotating/scaling it, the mesh suddenly

**Comment by m-r-davari** [comment] 2024-09-08 12:55
you have this issue on iOS right? did you experience this issue with web or android?

**Comment by gputhige** [comment] 2024-09-09 05:31
This was on Android Phone.

**Comment by m-r-davari** [comment] 2024-09-17 20:28
I found the cause, it takes too much effort but I almost fixed it 💪🏼, will be release in next version.
I will notify here when I released next version

**Comment by gputhige** [comment] 2024-09-18 08:23
Good News. Thanks for the effort. Looking forward to the new release.

**Comment by m-r-davari** [comment] 2024-10-05 05:46
Issue has been fixed with **Gesture Interceptor** feature released on v2.0.0.
[Check out new version](https://pub.dev/packages/flutter_3d_controller)

**Closed by m-r-davari** 2024-10-05 05:46 UTC
Labels: bug

**Comment by gputhige** [comment] 2024-10-06 08:17
Thanks for the quick action. Much appreciated. Will update to the latest version.

**Comment by gputhige** [comment] 2025-03-17 13:58
Hi
My Android App uses this plugin and it works perfectly fine. 
Now, I am uploading the webApp version to AWS. The .glb file is stored in S3 bucket and I have also included the head script inside the index.html file. 
<script type="module" src="./assets/packages/flutter_3d_controller/assets/model_viewer.min.js" defer></script>

However, the glb file does not render and is showing a blank screen. Any suggestions on this? Thanks in advance.
